server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://dpg-d81ciat0lvsc7399mqm0-a.oregon-postgres.render.com:5432/food_delvery_app
    username: food_delvery_app_user
    password: bneRXbwoToUiXzvYmfQGe809GIQ5hMY4
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
jwt:
  secret: mysecretkeymysecretkeymysecretkey123456
  expiration: 86400000